version: 0.0
os: linux
files:
  - source: /application.py
    destination: /home/ec2-user/eb_flask_app
hooks:
  AfterInstall:
    - location: scripts/start_server
      timeout: 180
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root