version: 0.0
os: linux
files:
  - source: /application.py
    destination: /home/ec2-user/eb_flask_app
  - source: templates
    destination: /home/ec2-user/eb_flask_app/templates
hooks:
  BeforeInstall:
    - location: scripts/cleanup
      timeout: 180
      runas: root
  AfterInstall:
    - location: scripts/start_server
      timeout: 180
      runas: root
  ApplicationStop:
    - location: scripts/stop_server2
      timeout: 300
      runas: root
